language: cpp
env:
  - CC=gcc CXX=gcc
  - CC=clang CXX=clang++
  - NODE4=true
  - NODE5=true
  - NODE012=true
install:
  - if [ "${NODE4}" ]; then export CC=gcc-4.8 CXX=g++-4.8; fi
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo add-apt-repository --yes ppa:fenics-packages/fenics-exp/swig
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq swig3.0 python git cmake
  - sudo ln -s /usr/bin/swig3.0 /usr/bin/swig
  - sudo update-java-alternatives -s java-8-oracle
before_script:
  - nvm install 0.10
  - if [ "$CC" = "gcc" ]; then export BUILDJAVA=ON; else export BUILDJAVA=OFF; fi
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - if [ "${NODE4}" ]; then nvm install 4.1; export CC=gcc-4.8; export CXX=g++-4.8; fi
  - if [ "${NODE5}" ]; then nvm install 5; export CC=gcc-4.8; export CXX=g++-4.8; fi
  - if [ "${NODE012}" ]; then nvm install 0.12; fi
script:
  - mkdir build && cd build && cmake -DBUILDSWIGJAVA=$BUILDJAVA -DNODE_ROOT_DIR:PATH="/home/travis/.nvm/versions/node/`nvm version`/include" .. && make && make test
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
